layout_spectrum: 0.17839230364188552
typography_spectrum: 0.5693659058306366
color:
  saturation: 0
  brandStrength: 0
  lightness: 0
  brandColors:
    - '#f5f5f5'
    - '#030303'
    - '#d2d2d2'
    - '#888888'
    - '#515151'
  rhythmicContrast: 0.8
title: ''
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: '- i read you -'
    url: 'http://www.infinityvisuals.com/contact/'
    type: external
  - name: '- pics -'
    url: 'https://thegrid.ai/test-u01je/'
    type: external
favicon: null
name: INFINITY âˆž VISUALS - fine art photography - more
author:
  name: Israel Valencia
  email: israelv@infinityvisuals.com
  url: www.infinityvisuals.com
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
